version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "3000"
    environment:
      - PORT=3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - internal
    dns:
      - 8.8.8.8
      - 1.1.1.1


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - kripto-redis
      - kripto-db
    restart: unless-stopped
    networks:
      - internal
    dns:
      - 8.8.8.8
      - 1.1.1.1


  kripto-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kriptobots
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  kripto-redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - internal

  kripto_nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - internal

volumes:
  redis_data:
  postgres_data:

networks:
  internal:
    driver: bridge
